name: Deploy to UAT Sandbox
run-name: ${{ github.actor }} is running the Github Actions 🚀
## Pipeline will be running mainly on 2 events most of the time 
### push, pull_request
on: 
  pull_request:
    types: [closed]
    paths:
      - 'force-app/**'
    branches:
      - UAT
jobs:
  build-and-deploy: ## Name of the Job
    runs-on: ubuntu-latest ## Github Hosted [Self Hosted]
    steps:
      - run: echo "This is my first Job"
        name: "First Job Message"
      - name: Checkout Code
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - name: npm install
        run: npm install
        ## Install Saleforce CLI
      - name: Install Salesforce CLI
        run: npm install @salesforce/cli --global
      - name: Decrypt the server.key  file
        run: openssl enc -nosalt -aes-256-cbc -d -in ${{secrets.ENCRYPTED_KEY_FILE_UAT}}  -out ${{secrets.JWT_KEY_FILE_UAT}}  -base64 -K ${{secrets.KEY_UAT}}  -iv ${{secrets.IV_UAT}}
      - name: Authorize the org
        run: sf login org jwt --username ${{secrets.SF_UAT_USER}} --keyfile ${{ secrets.JWT_KEY_FILE_UAT }} --clientid ${{secrets.SF_CLIENT_ID_UAT}}  --alias UAT  --instance-url ${{secrets.SF_INSTANCE_TEST_URL}}
      - name: Print the login org 
        run: sf org display user -o UAT

      - name: Deploy the code to salesforce
        run: sf project deploy start --source-dir force-app -o UAT
      
      

  clean-up:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is my second Job"
        name: "Print Message"