name: Check run

on: [push, pull_request]

jobs:
  check-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - run: sudo apt-get update && sudo apt-get install -y nginx && sudo systemctl start nginx

    - name: ZAP Scan
      uses: ./
      id: action-baseline
      with:
        target: 'http://localhost'
        allow_issue_writing: false