name: Security scan 
on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://computing-flow-9170.lightning.force.com'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -r zap_report.html'  # Generate HTML report
        continue-on-error: true  # Ensure build doesn't fail on scan failure

      - name: Upload ZAP Scan Report as Artifact
        if: always()  # This ensures the step runs even if previous step fails
        uses: actions/upload-artifact@v3
        with:
          name: zap-scan-report
          path: zap_report.html  # Path to the generated ZAP report
