name: Security Test

on: [push, pull_request]

jobs:
  owasp-zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start OWASP ZAP scan
        run: |
          docker run -t owasp/zap2docker-stable zap-baseline.py \
            -t https://clarienbank--developer.sandbox.my.site.com/s/ \
            -r zap_report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: zap_report.html
